apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: v1.5.3
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 10m
