apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hornhorse-external-dns
  namespace: hornhorse
spec:
  chart:
    spec:
      chart: external-dns
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  interval: 10m
  values:
    domainFilters: [horn.horse]
    provider: cloudflare
    extraArgs:
    - --zone-id-filter=97484d668a8bc6fa2ebbb4955f51a4f4
    env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: hornhorse-cloudflare
          key: cloudflare_api_token
    nodeSelector:
      kubernetes.io/arch: amd64
