apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: internal-contour
  namespace: internal-ingress
spec:
  chart:
    spec:
      chart: contour
      version: 2.3.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: gotk-system
  interval: 10m
  values:
    ingressClass: internal
    contour:
      nodeSelector: {}
    configInline: {}
    envoy:
      image:
        repository: envoyproxy/envoy
        tag: v1.16.0
      nodeSelector: {}
      service: {}
    prometheus:
      serviceMonitor:
        enabled: true
