apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: internal-nginx
  namespace: internal-ingress
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.0.6
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 10m
  values:
    controller:
      ingressClassResource:
        name: internal
      nodeSelector: {}
      service: {}

