apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secret-generator
  namespace: secret-generator
spec:
  chart:
    spec:
      chart: kubernetes-secret-generator
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: mittwald
        namespace: gotk-system
  interval: 10m
  values:
    nodeSelector: {}
