apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # see the "Cluster Settings" section below for more details on which image of ceph to run
    image: quay.io/ceph/ceph:v16.2.5
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: true
  monitoring:
    enabled: true
  mon:
    count: 3
    allowMultiplePerNode: true
  storage:
    useAllNodes: false
    useAllDevices: false
#    config:
#      metadataDevice: storberry-ssd
    nodes:
    - name: wpi-garnet
      devices:
      - name: /dev/disk/by-id/usb-WD_My_Passport_0748_575844314537324E43583737-0:0
    - name: wpi-amethyst
      devices:
      - name: /dev/disk/by-id/usb-Seagate_Portable_NAAHGF0V-0:0
    - name: wpi-pearl
      devices:
      - name: /dev/disk/by-id/usb-WD_Elements_2621_575843324531303454545741-0:0

