apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  chart:
    spec:
      chart: rook-ceph
      version: 1.4.5
      sourceRef:
        kind: HelmRepository
        name: rook-release
  interval: 10m
  values:
    csi:
      cephcsi:
        image: quay.io/cephcsi/cephcsi:v3.1.1
      registrar:
        image: raspbernetes/csi-node-driver-registrar:1.3.0
      provisioner:
        image: k8s.gcr.io/sig-storage/csi-provisioner:v1.6.0
      snapshotter:
        image: k8s.gcr.io/sig-storage/csi-snapshotter:v2.1.1
      attacher:
        image: k8s.gcr.io/sig-storage/csi-attacher:v2.2.0
      resizer:
        image: k8s.gcr.io/sig-storage/csi-resizer:v0.4.0
