apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # see the "Cluster Settings" section below for more details on which image of ceph to run
    image: ceph/ceph:v15.2.5
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: true
  monitoring:
    enabled: true
  mon:
    count: 3
    allowMultiplePerNode: true
  driveGroups:
  - name: storberry
    spec:
      db_devices:
        size: ':128G'
      data_devices:
        size: '1T:'
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: st8s.testtrack4.com/storage-group
              operator: In
              values:
              - storberry
