apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hornhorse-external-dns
  namespace: hornhorse
spec:
  chart:
    spec:
      chart: external-dns
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 10m
  values:
    domainFilters: [horn.horse]
    zoneIdFilters: ["97484d668a8bc6fa2ebbb4955f51a4f4"]
    provider: cloudflare
    cloudflare:
      secretName: hornhorse-cloudflare
      proxied: false
    nodeSelector:
      kubernetes.io/arch: amd64
