apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pomerium
  namespace: pomerium
spec:
  chart:
    spec:
      chart: pomerium
      version: 13.0.0
      sourceRef:
        kind: HelmRepository
        name: pomerium
        namespace: gotk-system
  interval: 10m
  values:
    config:
      policy: []
