apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pomerium
  namespace: pomerium
spec:
  chart:
    spec:
      chart: pomerium
      version: 23.2.0
      sourceRef:
        kind: HelmRepository
        name: pomerium
        namespace: flux-system
  interval: 10m
  values:
    config:
      policy: []
    nodeSelector: {}
    forwardAuth:
      enabled: true
      internal: true
      name: https://pomerium-proxy.pomerium.svc.cluster.local
  valuesFrom:
  - kind: Secret
    name: pomerium-config-secrets
    valuesKey: sharedSecret
    targetPath: config.sharedSecret
  - kind: Secret
    name: pomerium-config-secrets
    valuesKey: cookieSecret
    targetPath: config.cookieSecret
