apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  chart:
    spec:
      chart: node-feature-discovery
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  interval: 10m
