apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart:
    spec:
      chart: metallb
      version: 0.1.24
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: gotk-system
  interval: 10m
  values:
    controller:
      image:
        repository: metallb/controller
        tag: v0.9.3
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.9.3
      resources:
        requests:
          memory: 25Mi
          cpu: 25m
        limits:
          cpu: 100m
          memory: 100Mi
    configInline: |
      address-pools:
      - name: household-static
        protocol: layer2
        addresses:
        - 192.168.42.0 - 192.168.42.250
        auto-assign: false
      - name: household-dynamic
        protocol: layer2
        addresses:
        - 192.168.32.0 - 192.168.32.250
    prometheus:
      serviceMonitor:
        enabled: true
