apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart:
    spec:
      chart: metallb
      version: 2.5.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m
  values:
    controller:
      image:
        repository: metallb/controller
        tag: v0.10.2
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.10.2
    prometheus:
      serviceMonitor:
        enabled: true
