apiVersion: v1
kind: Namespace
metadata:
  name: stubernetes-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: stubernetes-system
  namespace: stubernetes-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/stuartpb/stubernetes.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  creationTimestamp: null
  name: stubernetes-system
  namespace: stubernetes-system
spec:
  interval: 10m0s
  path: ./system/local
  prune: true
  sourceRef:
    kind: GitRepository
    name: stubernetes-system
