apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kured
spec:
  chart:
    spec:
      chart: kured
      version: 2.10.0
      sourceRef:
        kind: HelmRepository
        name: kured
        namespace: flux-system
  interval: 10m
  values:
    updateStrategy: RollingUpdate
    image:
      repository: docker.io/raspbernetes/kured
    metrics:
      create: true
      namespace: kured
    service:
      create: true
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
