apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kured
spec:
  chart:
    spec:
      chart: kured
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: kured
        namespace: gotk-system
  interval: 10m
  values:
    image:
      repository: docker.io/raspbernetes/kured
    ## not sure I trust the chart's Prometheus stuff to work with this
    ## see https://github.com/weaveworks/kured/pull/209
    # metrics:
    #   create: true
    #   namespace: kured
    # service:
    #   create: true
    #   annotations:
    #     prometheus.io/scrape: "true"
    #     prometheus.io/path: "/metrics"
    #     prometheus.io/port: "8080"
