apiVersion: v1
kind: Namespace
metadata:
  name: pomerium
---
apiVersion: v1
kind: Secret
metadata:
  name: hornhorse-github
  namespace: pomerium # for authenticator
type: Opaque
stringData:
  IDP_PROVIDER: "github"
  IDP_CLIENT_ID: "{{INSERT_CLIENT_ID_HERE}}"
  IDP_CLIENT_SECRET: "{{INSERT_CLIENT_SECRET_HERE}}"
