apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: hornhorse
---
apiVersion: v1
kind: Secret
metadata:
  name: hornhorse-cloudflare
  namespace: cert-manager # for ACME DNS-01
type: Opaque
stringData:
  cloudflare_api_token: "{{INSERT_TOKEN_HERE}}"
---
apiVersion: v1
kind: Secret
metadata:
  name: hornhorse-cloudflare
  namespace: hornhorse # for external-dns
type: Opaque
stringData:
  cloudflare_api_token: "{{INSERT_TOKEN_HERE}}"

