apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: bulk
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-bulk-pool"
      - name: ReplicaCount
        value: "1"
provisioner: openebs.io/provisioner-iscsi
---
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-bulk-pool
  namespace: openebs
  annotations:
    cas.openebs.io/config: |
      - name: PoolResourceRequests
        value: |-
            memory: 100Mi
      - name: PoolResourceLimits
        value: |-
            memory: 4Gi
spec:
  name: cstor-bulk-pool
  type: disk
  poolSpec:
    poolType: striped
  blockDevices:
    blockDeviceList:
    - blockdevice-9d50e42f15fe83269356445eea81b1e2
