apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-work-pool
  namespace: openebs
  annotations:
    cas.openebs.io/config: |
      - name: PoolResourceRequests
        value: |-
            memory: 100Mi
      - name: PoolResourceLimits
        value: |-
            memory: 4Gi
spec:
  name: cstor-work-pool
  type: disk
  poolSpec:
    poolType: striped
  blockDevices:
    blockDeviceList:
    - blockdevice-50bfc93f4a03ff39b6219fed5965fe7b
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-work
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-work-pool"
      - name: ReplicaCount
        value: "1"
provisioner: openebs.io/provisioner-iscsi
