apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  chart:
    spec:
      chart: rook-ceph
      version: 1.4.5
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: gotk-system
  interval: 10m
  values:
    csi:
      cephcsi:
        image: quay.io/cephcsi/cephcsi:v3.1.1
      registrar:
        image: docker.io/raspbernetes/csi-node-driver-registrar:1.3.0
      provisioner:
        image: docker.io/raspbernetes/csi-external-provisioner:1.6.0
      snapshotter:
        image: docker.io/raspbernetes/csi-external-snapshotter:2.1.1
      attacher:
        image: docker.io/raspbernetes/csi-external-attacher:2.2.0
      resizer:
        image: docker.io/raspbernetes/csi-external-resizer:0.5.0
