apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  chart:
    spec:
      chart: rook-ceph
      version: 1.7.2
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
  interval: 10m
