apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ./nodes.yaml
- ./hats
- ./storage
#- ./zones/403 # patches only
- ./zones/hornhorse
- ./issuers
#- ./arch-pinning # patches only
- ./chart-forks
#- ./compute-resources # patches only

patches:

# ./hats
- target:
    kind: Node
    version: v1
    name: wpi-pearl
  path: ./hats/argon1.nodes.patch.yaml

# ./storage
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: kube-prometheus-stack
    namespace: prometheus
  path: ./storage/kube-prometheus-stack.helmrelease.patch.yaml
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: pomerium
    namespace: pomerium
  path: ./storage/pomerium.helmrelease.patch.yaml

# ./storage/storberry
- target:
    kind: Node
    version: v1
    name: wpi-(garnet|amethyst|pearl)
  path: ./storage/storberry/storberry.nodes.patch.yaml

# ./zones/403
- target:
    kind: Node
    version: v1
    name: (mpi-rose|wpi-(garnet|amethyst|pearl)|wpc-(gomez|morticia))
  path: ./zones/403/zone-403.nodes.patch.yaml
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: internal-nginx
    namespace: internal-ingress
  path: ./zones/403/internal-nginx.helmrelease.patch.yaml
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: metallb
    namespace: metallb-system
  path: ./zones/403/metallb.helmrelease.patch.yaml

# ./zones/hornhorse
- target:
    kind: ClusterIssuer
    name: stuartpb-letsencrypt(-staging)?
  path: ./zones/hornhorse/hornhorse-acme-solver.clusterissuer.patch.yaml
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: pomerium
    namespace: pomerium
  path: ./zones/hornhorse/pomerium.helmrelease.patch.yaml

# ./zones/hornhorse/ingress
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: pomerium
    namespace: pomerium
  path: ./zones/hornhorse/ingress/pomerium-ingress.helmrelease.patch.yaml
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: pomerium
    namespace: pomerium
  path: ./zones/hornhorse/ingress/pomerium-policies.helmrelease.patch.yaml

# ./arch-pinning
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: internal-contour
    namespace: internal-ingress
  path: ./arch-pinning/internal-contour.helmrelease.patch.yaml
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: kube-prometheus-stack
    namespace: prometheus
  path: ./arch-pinning/kube-prometheus-stack.helmrelease.patch.yaml
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: pomerium
    namespace: pomerium
  path: ./arch-pinning/pomerium.helmrelease.patch.yaml

# ./chart-forks
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: pomerium
    namespace: pomerium
  path: ./chart-forks/pomerium.helmrelease.patch.yaml

# ./compute-resources
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: internal-contour
    namespace: internal-ingress
  path: ./compute-resources/internal-contour.helmrelease.patch.yaml
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: kubernetes-dashboard
    namespace: kubernetes-dashboard
  path: ./compute-resources/kubernetes-dashboard.helmrelease.patch.yaml
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: metallb
    namespace: metallb-system
  path: ./compute-resources/metallb.helmrelease.patch.yaml
