apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

# base components
- ./crds
- ./helmrepositories
- ./metallb
- ./cert-manager
- ./node-feature-discovery
- ./rook-ceph
- ./internal-ingress
- ./kube-prometheus-stack
- ./kubernetes-dashboard

# local kustomizations
- ./nodes.yaml
- ./local/hats
- ./local/storage
#- ./local/zones/403 # patches only
- ./local/zones/hornhorse
- ./local/issuers
#- ./local/arch-pinning # patches only
#- ./local/compute-resources # patches only

patches:

# ./local/hats
- target:
    kind: Node
    version: v1
    name: wpi-pearl
  path: ./local/hats/argon1.nodes.patch.yaml

# ./local/storage
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: kube-prometheus-stack
    namespace: prometheus
  path: ./local/storage/kube-prometheus-stack.helmrelease.patch.yaml

# ./local/storage/storberry
- target:
    kind: Node
    version: v1
    name: wpi-garnet # wpi-(garnet|amethyst|pearl)
  path: ./local/storage/storberry/storberry.nodes.patch.yaml
- target:
    kind: Node
    version: v1
    name: wpi-amethyst # wpi-(garnet|amethyst|pearl)
  path: ./local/storage/storberry/storberry.nodes.patch.yaml
- target:
    kind: Node
    version: v1
    name: wpi-pearl # wpi-(garnet|amethyst|pearl)
  path: ./local/storage/storberry/storberry.nodes.patch.yaml

# ./local/zones/403
- target:
    kind: Node
    version: v1
    name: mpi-rose # (mpi-rose|wpi-(garnet|amethyst|pearl)|wpc-(gomez|morticia))
  path: ./local/zones/403/zone-403.nodes.patch.yaml
- target:
    kind: Node
    version: v1
    name: wpi-garnet # (mpi-rose|wpi-(garnet|amethyst|pearl)|wpc-(gomez|morticia))
  path: ./local/zones/403/zone-403.nodes.patch.yaml
- target:
    kind: Node
    version: v1
    name: wpi-amethyst # (mpi-rose|wpi-(garnet|amethyst|pearl)|wpc-(gomez|morticia))
  path: ./local/zones/403/zone-403.nodes.patch.yaml
- target:
    kind: Node
    version: v1
    name: wpi-pearl # (mpi-rose|wpi-(garnet|amethyst|pearl)|wpc-(gomez|morticia))
  path: ./local/zones/403/zone-403.nodes.patch.yaml
- target:
    kind: Node
    version: v1
    name: wpc-gomez # (mpi-rose|wpi-(garnet|amethyst|pearl)|wpc-(gomez|morticia))
  path: ./local/zones/403/zone-403.nodes.patch.yaml
- target:
    kind: Node
    version: v1
    name: wpc-morticia # (mpi-rose|wpi-(garnet|amethyst|pearl)|wpc-(gomez|morticia))
  path: ./local/zones/403/zone-403.nodes.patch.yaml
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: internal-contour
    namespace: internal-ingress
  path: ./local/zones/403/internal-contour.helmrelease.patch.yaml
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: metallb
    namespace: metallb-system
  path: ./local/zones/403/metallb.helmrelease.patch.yaml

patches:

# ./local/zones/hornhorse
- target:
    kind: ClusterIssuer
    name: stuartpb-letsencrypt
  path: ./local/zones/hornhorse/hornhorse-acme-solver.clusterissuer.patch.yaml
- target:
    kind: ClusterIssuer
    name: stuartpb-letsencrypt-staging
  path: ./local/zones/hornhorse/hornhorse-acme-solver.clusterissuer.patch.yaml

# ./local/zones/hornhorse/ingress
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: kubernetes-dashboard
    namespace: kubernetes-dashboard
  path: ./local/zones/hornhorse/ingress/kubernetes-dashboard.helmrelease.patch.yaml
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: kube-prometheus-stack
    namespace: prometheus
  path: ./local/zones/hornhorse/ingress/kube-prometheus-stack.helmrelease.patch.yaml

# ./local/arch-pinning
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: internal-contour
    namespace: internal-ingress
  path: ./local/arch-pinning/internal-contour.helmrelease.patch.yaml
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: kube-prometheus-stack
    namespace: prometheus
  path: ./local/arch-pinning/kube-prometheus-stack.helmrelease.patch.yaml

# ./local/compute-resources
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: internal-contour
    namespace: internal-ingress
  path: ./local/compute-resources/internal-contour.helmrelease.patch.yaml
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: kubernetes-dashboard
    namespace: kubernetes-dashboard
  path: ./local/compute-resources/kubernetes-dashboard.helmrelease.patch.yaml
- target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    name: metallb
    namespace: metallb-system
  path: ./local/compute-resources/metallb.helmrelease.patch.yaml
