apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: node-feature-discovery
  namespace: flux-system
spec:
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
  interval: 30m
