apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./crds
- ./helmrepositories
- ./metallb
- ./cert-manager
- ./node-feature-discovery
- ./rook-ceph
- ./internal-ingress
- ./hornhorse
- ./kube-prometheus-stack
- ./kubernetes-dashboard
