apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./crds
- ./helmrepositories
- ./metallb
- ./cert-manager
- ./node-feature-discovery
- ./secret-generator
- ./kured
- ./rook-ceph
- ./internal-ingress
- ./kube-prometheus-stack
- ./pomerium
- ./kubernetes-dashboard
