- op: add
  path: /spec/values/prometheus/ingress
  value:
    enabled: true
    hosts: [prometheus.horn.horse]
    tls:
    - secretName: prometheus-hornhorse-cert
      hosts: [prometheus.horn.horse]
    annotations:
      cert-manager.io/cluster-issuer: stuartpb-letsencrypt-staging
      ingress.kubernetes.io/force-ssl-redirect: "true"
      kubernetes.io/ingress.class: internal
      kubernetes.io/tls-acme: "true"
- op: add
  path: /spec/values/alertmanager/ingress
  value:
    enabled: true
    hosts: [alertmanager.horn.horse]
    tls:
    - secretName: alertmanager-hornhorse-cert
      hosts: [alertmanager.horn.horse]
    annotations:
      cert-manager.io/cluster-issuer: stuartpb-letsencrypt-staging
      ingress.kubernetes.io/force-ssl-redirect: "true"
      kubernetes.io/ingress.class: internal
      kubernetes.io/tls-acme: "true"
- op: add
  path: /spec/values/grafana/ingress
  value:
    enabled: true
    hosts: [grafana.horn.horse]
    tls:
    - secretName: grafana-hornhorse-cert
      hosts: [grafana.horn.horse]
    annotations:
      cert-manager.io/cluster-issuer: stuartpb-letsencrypt-staging
      ingress.kubernetes.io/force-ssl-redirect: "true"
      kubernetes.io/ingress.class: internal
      kubernetes.io/tls-acme: "true"
