- op: add
  path: /spec/values/ingress
  value:
    annotations:
      cert-manager.io/cluster-issuer: stuartpb-letsencrypt-staging
      ingress.kubernetes.io/force-ssl-redirect: "true"
      kubernetes.io/ingress.class: internal
      kubernetes.io/tls-acme: "true"
    secret:
      name: pomerium-hornhorse-cert
