- op: add
  path: /spec/values/ingress
  value:
    className: internal
    annotations:
      cert-manager.io/cluster-issuer: stuartpb-letsencrypt-staging
      ingress.kubernetes.io/force-ssl-redirect: "true"
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    secret:
      name: pomerium-hornhorse-cert
