apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: prometheus
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 10.1.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 10m
  values:
    fullnameOverride: kps
    prometheus:
      prometheusSpec:
        nodeSelector: {}
    prometheusOperator:
      nodeSelector: {}
    alertmanager: {}
    kube-state-metrics:
      nodeSelector: {}
    grafana:
      nodeSelector: {}
      grafana.ini:
        auth.proxy:
          enabled: true
          header_name: X-Pomerium-Claim-Email
          header_property: email
