apiVersion: v1
kind: Namespace
metadata:
  name: household-system
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: household-internal-dns
  namespace: stubernetes-system
spec:
  releaseName: household-internal-dns
  targetNamespace: household-system
  chart:
    git: https://github.com/stuartpb/inhouse-dns.git
    ref: v0.1.2
    path: '/'
  values:
    coredns:
      resources:
        limits:
          cpu: 1
      serviceType: LoadBalancer
      service:
        annotations:
          metallb.universe.tf/allow-shared-ip: "true"
        loadBalancerIP: 192.168.42.53
      # NOTE: we don't provide the Prometheus Operator ServiceMonitor CRD,
      # so make sure it's installed first
      prometheus:
        service:
          enabled: true
        monitor:
          enabled: true
    external-dns:
      annotationFilter: kubernetes.io/ingress.class=internal
      coredns:
        etcdEndpoints: "http://household-internal-dns-etcd.household-system.svc.cluster.local:2379"
      nodeSelector:
        kubernetes.io/arch: amd64
    etcd:
      nodeSelector:
        kubernetes.io/arch: amd64
