apiVersion: v1
kind: Namespace
metadata:
  name: household-system
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: household-contour
  namespace: stubernetes-system
spec:
  releaseName: household-contour
  targetNamespace: household-system
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: contour
    version: 2.0.0
  values:
    contour:
      nodeSelector:
        kubernetes.io/arch: amd64
      resources:
        limits:
          cpu: 400m
          memory: 250Mi
        requests:
          cpu: 100m
          memory: 25Mi
    envoy:
      resources:
        limits:
          cpu: 400m
          memory: 250Mi
        requests:
          cpu: 100m
          memory: 25Mi
      nodeSelector:
        st8s.testtrack4.com/zone: "403"
    prometheus:
      serviceMonitor:
        enabled: true
