apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: stubernetes-system
spec:
  releaseName: prometheus-operator
  targetNamespace: prometheus
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: prometheus-operator
    version: 8.15.8
  values:
    fullnameOverride: pop
    prometheus:
      prometheusSpec:
        nodeSelector:
          kubernetes.io/arch: amd64
      ingress:
        hosts: [alerts.prometheus.internal]
        annotations:
          st8s.stuartpb.com/zone: "403"
    grafana:
      ingress:
        hosts: [grafana.prometheus.internal]
        annotations:
          st8s.stuartpb.com/zone: "403"
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: ps # additional protection against https://github.com/helm/charts/issues/13170
        spec:
          storageClassName: bulk
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
