apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: stubernetes-system
spec:
  releaseName: rook-ceph
  targetNamespace: rook-ceph
  chart:
    repository: https://charts.rook.io/release
    name: rook-ceph
    version: 1.4.5
  values:
    csi:
      cephcsi:
        image: quay.io/cephcsi/cephcsi:v3.1.1
      registrar:
        image: raspbernetes/csi-node-driver-registrar:1.3.0
      provisioner:
        image: k8s.gcr.io/sig-storage/csi-provisioner:v1.6.0
      snapshotter:
        image: k8s.gcr.io/sig-storage/csi-snapshotter:v2.1.1
      attacher:
        image: k8s.gcr.io/sig-storage/csi-attacher:v2.2.0
      resizer:
        image: k8s.gcr.io/sig-storage/csi-resizer:v0.4.0
