apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: stubernetes-system
spec:
  releaseName: rook-ceph
  targetNamespace: rook-ceph
  chart:
    repository: https://charts.rook.io/release
    name: rook-ceph
    version: 1.3.7
  values:
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
