apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: stubernetes-system
spec:
  releaseName: rook-ceph
  targetNamespace: rook-ceph
  chart:
    repository: https://charts.rook.io/release
    name: rook-ceph
    version: 1.4.4
  values:
    image:
      tag: v1.4.4-17.gd86d6cd
