apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: gotk-system
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: 30m
