apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: prometheus
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 9.4.8
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 10m
  values:
    fullnameOverride: kps
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: throwaway
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
        nodeSelector:
          kubernetes.io/arch: amd64
      ingress:
        enabled: true
        hosts: [prometheus.horn.horse]
        tls:
        - secretName: prometheus-hornhorse-cert
          hosts: [prometheus.horn.horse]
        annotations:
          cert-manager.io/cluster-issuer: hornhorse-staging-issuer
          ingress.kubernetes.io/force-ssl-redirect: "true"
          kubernetes.io/ingress.class: internal
          kubernetes.io/tls-acme: "true"
    prometheusOperator:
      nodeSelector:
        kubernetes.io/arch: amd64
    alertmanager:
      ingress:
        enabled: true
        hosts: [alertmanager.horn.horse]
        tls:
        - secretName: alertmanager-hornhorse-cert
          hosts: [alertmanager.horn.horse]
        annotations:
          cert-manager.io/cluster-issuer: hornhorse-staging-issuer
          ingress.kubernetes.io/force-ssl-redirect: "true"
          kubernetes.io/ingress.class: internal
          kubernetes.io/tls-acme: "true"
    kube-state-metrics:
      nodeSelector:
        kubernetes.io/arch: amd64
    grafana:
      ingress:
        enabled: true
        hosts: [grafana.horn.horse]
        tls:
        - secretName: grafana-hornhorse-cert
          hosts: [grafana.horn.horse]
        annotations:
          cert-manager.io/cluster-issuer: hornhorse-staging-issuer
          ingress.kubernetes.io/force-ssl-redirect: "true"
          kubernetes.io/ingress.class: internal
          kubernetes.io/tls-acme: "true"
      nodeSelector:
        kubernetes.io/arch: amd64
